export const portfolioConfig = {
    siteTitle: 'Aeiyan Khan',
    tagline: 'Full-Stack Engineer & Project Manager',
    heroDescription: [
        { text: "Hi, I'm Aeiyan. I ", highlight: false },
        { text: "build web apps", highlight: true },
        { text: " and ", highlight: false },
        { text: "lead the teams", highlight: true },
        { text: " that ship them. I've worked on products in ", highlight: false },
        { text: "healthcare, fintech, food delivery, and hospitality", highlight: true },
        { text: " — and I currently manage multiple product teams at ", highlight: false },
        { text: "Samarix", highlight: true },
        { text: " while teaching developers at SMIT on the side.", highlight: false },
    ],
    aboutDescription: [
        { text: "I started coding at ", highlight: false },
        { text: "17", highlight: true },
        { text: " out of pure curiosity. I didn't have a plan — I just wanted to understand how websites worked. That curiosity turned into a career, and I haven't looked back since.", highlight: false },

        { text: " I'm based in ", highlight: false },
        { text: "Hyderabad, Pakistan", highlight: true },
        { text: ". Right now I'm a ", highlight: false },
        { text: "Project Manager at Samarix", highlight: true },
        { text: ", where I coordinate teams and delivery across several live client products — from a food delivery app to an AI tool for real estate agents.", highlight: false },

        { text: " Before moving into management, I was deep in the code — building backends with ", highlight: false },
        { text: "Node.js and NestJS", highlight: true },
        { text: ", architecting real-time systems, and contributing to platforms that serve thousands of real users in Pakistan.", highlight: false },

        { text: " I also teach at ", highlight: false },
        { text: "Saylani Mass IT Training (SMIT)", highlight: true },
        { text: ", where I've guided 80+ students through building their first real-world web apps.", highlight: false },

        { text: " Outside of work, I care about building things that are simple to use, honest in what they do, and maintainable by whoever comes next.", highlight: false },
    ],
    experience: [
        {
            id: "samarix-pm",
            companyName: "Samarix",
            position: "Project Manager",
            from: "July 2026",
            to: "Present",
            website: "https://samarix.com/",
            barPosition: -10,
            barAbovePosition: 100,
            tasks: [
                {
                    text: "Managing delivery across multiple concurrent client products — Jayak Hub (food delivery), Listr AI (AI tool for real estate), and SiteFlows (rental operations).",
                    keywords: ["Jayak Hub", "Listr AI", "SiteFlows"],
                },
                {
                    text: "Running weekly planning and coordination meetings with designers and engineering team leads across all active projects.",
                    keywords: ["Team Coordination", "Planning", "Cross-Functional"],
                },
                {
                    text: "Assigning teams, setting timelines, and making sure design, engineering, and client requirements stay in sync.",
                    keywords: ["Delivery", "Leadership", "Client Projects"],
                },
                {
                    text: "Promoted from Full-Stack Developer to Project Manager in under a year — recognized for technical leadership and delivery impact.",
                    keywords: ["Promoted", "Leadership", "Recognition"],
                },
            ],
        },
        {
            id: "zetsol",
            companyName: "Zetsol Technologies",
            position: "MEAN & MERN Stack Developer",
            from: "December 2023",
            to: "January 2026",
            website: "https://zetsol.ae/",
            barPosition: -10,
            barAbovePosition: 100,
            tasks: [
                {
                    text: "Built and maintained backend APIs for Sehat Kahani — Pakistan's leading telemedicine platform, serving thousands of concurrent users.",
                    keywords: ["Sehat Kahani", "Telemedicine", "Healthcare"],
                },
                {
                    text: "Developed full-stack features for Neem, a digital financial platform — including KYC onboarding, wallet management, and lending workflows.",
                    keywords: ["Neem", "Fintech", "Digital Banking"],
                },
                {
                    text: "Worked across Angular and React frontends while building Node.js backends — often the same week.",
                    keywords: ["Angular", "React", "Node.js", "Full-Stack"],
                },
                {
                    text: "Awarded Employee of the Month (June 2024) for outstanding technical contribution.",
                    keywords: ["Employee of the Month", "Award", "Recognition"],
                },
            ],
        },
        {
            id: "smit",
            companyName: "Saylani Mass IT Training (SMIT)",
            position: "Web & App Development Instructor",
            from: "July 2025",
            to: "Present",
            website: "https://www.saylaniwelfare.com/",
            barPosition: 80,
            barAbovePosition: 256,
            tasks: [
                {
                    text: "Teaching full-stack web development — HTML, CSS, JavaScript, React, Node.js, and databases — to aspiring developers.",
                    keywords: ["Teaching", "Web Development", "MERN Stack"],
                },
                {
                    text: "Guided 80+ students through building complete real-world projects, from concept to deployment.",
                    keywords: ["Mentorship", "Project-Based Learning", "Deployment"],
                },
                {
                    text: "Covering Git, REST APIs, and deployment workflows — the practical stuff that actually matters on the job.",
                    keywords: ["Git", "REST APIs", "Vercel", "Netlify"],
                },
            ],
        },
    ],
    projectsData: [
        {
            title: "SentinelKids",
            projectType: "Office Project · Samarix",
            link: null,
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "AI-powered parental control platform with real-time monitoring",
            ownership: "Backend architecture using Kafka and Redis for sub-second processing",
            architectureSignal: "NestJS · Kafka · Redis · Real-time pipelines",
            description: "An AI-powered parental control platform. I engineered the backend using Kafka and Redis to handle real-time data streams — keeping monitoring latency under a second even under load.",
            tech: ["NestJS", "Kafka", "Redis", "TypeScript", "Real-time"],
            github: null,
        },
        {
            title: "Sehat Kahani",
            projectType: "Office Project · Zetsol Technologies",
            link: "https://sehatkahani.com",
            image: "/sehatkahani.png",
            background: "/sehatkahani-bg.jpg",
            outcome: "Pakistan's leading telemedicine platform",
            ownership: "Backend APIs, admin panels, doctor and patient web portals",
            architectureSignal: "Angular + Node.js · JWT auth · e-pharmacy & lab integrations",
            description: "Pakistan's leading telehealth platform, connecting patients with licensed doctors online. I built the backend APIs and admin portals covering teleconsultation, e-pharmacy, and lab orders.",
            tech: ["Angular", "Node.js", "MongoDB", "Web App"],
            github: null,
        },
        {
            title: "Neem",
            projectType: "Office Project · Zetsol Technologies",
            link: "https://neem.io",
            image: "/neem.png",
            background: "/neem-bg.jpg",
            outcome: "Digital financial platform for payments, lending, and wallets",
            ownership: "Full-stack modules and third-party payment integrations",
            architectureSignal: "Next.js · Node.js · KYC onboarding · secure transactions",
            description: "A digital banking platform for online payments, digital lending, and wallet management. I developed full-stack modules and integrated third-party payment and KYC services.",
            tech: ["Next.js", "Node.js", "Tailwind CSS", "Fintech", "Web App"],
            github: null,
        },
        {
            title: "Umah Shanti Villa",
            projectType: "Freelance Project",
            link: "https://vus-fe-zeta.vercel.app/",
            image: "/umahshanti.png",
            background: "/umahshanti-bg.jpg",
            outcome: "Luxury villa website with booking and guest testimonials",
            ownership: "Full-stack — booking flow, payment integration, responsive design",
            architectureSignal: "Next.js + Node.js · date-conflict prevention · Vercel",
            description: "A website for a luxury Bali villa — built to showcase rooms, handle booking inquiries, and display guest testimonials. Full-stack, including date conflict prevention and payment integration.",
            tech: ["Next.js", "Node.js", "Payment Integration", "Web App"],
            github: null,
        },
        {
            title: "Lawn Barber",
            projectType: "Freelance Project",
            link: null,
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "Website for a US lawn care business",
            ownership: "Full-stack — service listings, portfolio gallery, quote request form",
            architectureSignal: "Next.js · Tailwind CSS · responsive · Vercel",
            description: "A website for a lawn care business in the US — featuring service listings, a portfolio of past work, and a quote request flow. Clean, fast, and easy for the client to maintain.",
            tech: ["Next.js", "Tailwind CSS", "Web App"],
            github: null,
        },
        {
            title: "Jayak Hub",
            projectType: "Office Project · Samarix",
            link: null,
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "Food delivery platform — led as Project Manager",
            ownership: "Project management and backend contributions",
            architectureSignal: "Node.js · NestJS · Real-time order tracking",
            description: "A food delivery platform I manage at Samarix. I lead project delivery while continuing to contribute to the backend — keeping design, engineering, and the client in sync.",
            tech: ["Node.js", "NestJS", "TypeScript", "Web App"],
            github: null,
        },
        {
            title: "Listr AI",
            projectType: "Office Project · Samarix × Nortra LLC",
            link: null,
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "AI-powered lead response and follow-up tool for real estate teams",
            ownership: "Project management across design and engineering",
            architectureSignal: "AI · Lead automation · Real estate workflows",
            description: "An AI tool that automates lead responses and follow-ups for real estate teams, built by Nortra LLC. I led the project from the Samarix side — managing timelines, team coordination, and client delivery.",
            tech: ["AI", "Automation", "Web App"],
            github: null,
        },
        {
            title: "SiteFlows",
            projectType: "Office Project · Samarix",
            link: null,
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "Operations platform for short-term rental turnovers, cleanings, and damage reports",
            ownership: "Project management — coordinating design and engineering",
            architectureSignal: "Node.js · Operations management · Mobile-friendly",
            description: "A platform that helps short-term rental operators manage turnovers, schedule cleanings, and log damage reports. I lead the project at Samarix, keeping the product and client in sync throughout.",
            tech: ["Node.js", "TypeScript", "Web App"],
            github: null,
        },
        {
            title: "BC Appa",
            projectType: "Office Project · Zetsol Technologies",
            link: "https://bcappa.com",
            image: "/bcappa.png",
            background: "/bcapp-bg.jpg",
            outcome: "Rotating savings (committee) management platform",
            ownership: "Frontend admin dashboards, committee management UI, payout tracking",
            architectureSignal: "Next.js · Node.js · role-based views · contribution tracking",
            description: "An online platform for managing rotating savings committees (BC) — where groups of people take turns receiving a pooled monthly payout. I built the admin dashboards and member management interfaces.",
            tech: ["Next.js", "Node.js", "Tailwind CSS", "Web App"],
            github: null,
        },
        {
            title: "Elysium Dental & Aesthetics",
            projectType: "Freelance Project",
            link: "https://edac.com.pk/",
            image: "/project-1.png",
            background: "/ensvision.jpg",
            outcome: "Marketing and appointment site for a dental clinic",
            ownership: "Full ownership — design, development, performance, deployment",
            architectureSignal: "Next.js SSG · Tailwind CSS · optimized images · Vercel",
            description: "A fast, responsive marketing site for a dental clinic in Pakistan. Fully server-side generated for quick load times, with service pages, team info, and appointment details.",
            tech: ["Next.js", "Tailwind CSS", "SSG", "Web App"],
            github: null,
        },
    ],
};
